import{Button,Heading,Label,Spinner}from'@primer/react';
import{GitBranchIcon}from'@primer/octicons-react';
import{useQuery}from'@tanstack/react-query';
import{api}from'../../api';import{session}from'../../session';import type{PvpHistoryItem}from'../../types';

function Shell({themeButton,children}:{themeButton:React.ReactNode;children:React.ReactNode}){return <div className="app"><header className="masthead"><a className="brand-link" href="#/"><div className="brand"><span className="mark"><GitBranchIcon size={20}/></span><strong>GitHarbour</strong></div></a><nav className="identity"><a className="text-link" href="#/leaderboard">Leaderboard</a>{themeButton}</nav></header><main>{children}</main></div>}
function Refit({themeButton,onNeedAuth}:{themeButton:React.ReactNode;onNeedAuth:()=>void}){return <Shell themeButton={themeButton}><section className="challenge-page"><p className="eyebrow">Developer vs Developer</p><Heading as="h1">The harbour is being refitted.</Heading><p>PvP's challenge, identity, rating, and history infrastructure is preserved. New battles will use each developer's real contribution cells as hidden targets.</p><div className="mode-note"><strong>Next ruleset</strong><span>Choose an eligible ten-week contribution slice, take one shot per turn, and win by finding every target day.</span></div>{session.get()?<Button variant="primary" onClick={()=>location.hash='#/'}>Battle your own history</Button>:<Button variant="primary" onClick={onNeedAuth}>Continue with GitHub</Button>}</section></Shell>}
export function AuthenticatedPvp({themeButton,onNeedAuth}:{page:'new'|'battles'|'battle';param?:string;themeButton:React.ReactNode;onNeedAuth:()=>void}){return <Refit themeButton={themeButton} onNeedAuth={onNeedAuth}/>}
export function ChallengePage({themeButton,onNeedAuth}:{code:string;themeButton:React.ReactNode;onNeedAuth:()=>void}){return <Refit themeButton={themeButton} onNeedAuth={onNeedAuth}/>}

export function LeaderboardPage({themeButton}:{themeButton:React.ReactNode}){const query=useQuery({queryKey:['solo-leaderboard'],queryFn:api.leaderboard});return <Shell themeButton={themeButton}><section><div className="page-head"><div><p className="eyebrow">Current competition</p><Heading as="h1">Solo leaderboard</Heading><p>Standings from the active Battleship ruleset, ordered by Solo rating.</p></div><Label variant="success">Active</Label></div>{query.isLoading?<div className="loading-inline"><Spinner/><p>Loading standings…</p></div>:<div className="leaderboard-list"><div className="leaderboard-head"><span>Rank</span><span>Developer</span><span>Rating</span><span>Wins</span><span>Win rate</span></div>{(query.data?.entries||[]).map(entry=><a className="leaderboard-row" href={`#/u/${entry.login}`} key={entry.login}><strong>#{entry.position}</strong><span className="leaderboard-user"><img src={entry.avatarUrl} alt=""/><span><strong>@{entry.login}</strong><small>{entry.rank}</small></span></span><strong>{entry.rating}</strong><span>{entry.wins}</span><span>{entry.winRate.toFixed(0)}%</span></a>)}</div>}</section></Shell>}

export function PvpHistory({items=[]}:{items?:PvpHistoryItem[]}){if(!items.length)return <p className="empty-copy">No completed PvP battles yet.</p>;return <div className="history-list">{items.map(item=><a href={`${apiBaseForShare()}/s/${item.shareId}`} target="_blank" rel="noreferrer" key={item.id} className={item.result}><div><strong>{item.result==='victory'?'Victory':'Defeat'} vs @{item.opponent.login}</strong><small>{new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(new Date(item.completedAt))}</small></div><span><strong>{item.ratingDelta>=0?'+':''}{item.ratingDelta}</strong><small>{item.shots} shots</small></span></a>)}</div>}
function apiBaseForShare(){return import.meta.env.VITE_API_URL||'http://localhost:8080'}
